# Generated by Django 5.2.4 on 2025-08-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_latitude_customuser_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
