# Generated by Django 5.2.4 on 2025-08-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='together',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_codes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='together_input',
            field=models.CharField(default='혼자', max_length=10),
            preserve_default=False,
        ),
    ]
