# Generated by Django 5.2.4 on 2025-08-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_together_userprofile_theme_codes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fee_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='together_input',
            field=models.CharField(max_length=20),
        ),
    ]
