# Generated by Django 5.2.4 on 2025-08-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_surveyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyreview',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='review_photos/'),
        ),
    ]
