# Generated by Django 5.2.4 on 2025-08-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_surveyreview_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysubmission',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='certification_photos/'),
        ),
    ]
