# Generated by Django 5.2.4 on 2025-08-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_surveysubmission_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyreview',
            name='rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
