# Generated by Django 5.2.4 on 2025-08-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_surveyreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyreview',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
