# config.yml (Rasa 3.x)
version: "3.1"
language: ko

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
  # 단어 단위 BoW
- name: CountVectorsFeaturizer
  OOV_token: "__oov__"
  min_ngram: 1
  max_ngram: 1
  # 한글 형태 변화/띄어쓰기 보완용 문자 n-gram
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 3
  max_ngram: 5
- name: DIETClassifier
  epochs: 100
  learning_rate: 0.001
  constrain_similarities: true
- name: EntitySynonymMapper
- name: FallbackClassifier
  threshold: 0.4
  ambiguity_threshold: 0.1

policies:
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true
- name: MemoizationPolicy
  max_history: 5
- name: TEDPolicy
  max_history: 5
  epochs: 50
  constrain_similarities: true
assistant_id: 20250819-130214-heartless-circuit
