# Generated by Django 5.2.4 on 2025-08-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('guname', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=100)),
                ('place', models.CharField(blank=True, max_length=255)),
                ('org_name', models.CharField(blank=True, max_length=255)),
                ('use_trgt', models.CharField(blank=True, max_length=255)),
                ('use_fee', models.CharField(blank=True, max_length=255)),
                ('player', models.TextField(blank=True)),
                ('program', models.TextField(blank=True)),
                ('etc_desc', models.TextField(blank=True)),
                ('org_link', models.URLField(blank=True)),
                ('main_img', models.URLField(blank=True)),
                ('rgst_date', models.DateField(blank=True, null=True)),
                ('ticket', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('themecode', models.CharField(blank=True, max_length=100)),
                ('lot', models.CharField(blank=True, max_length=30)),
                ('lat', models.CharField(blank=True, max_length=30)),
                ('is_free', models.CharField(blank=True, max_length=10)),
                ('hmpg_addr', models.URLField(blank=True)),
            ],
        ),
    ]
