# Generated by Django 5.2.4 on 2025-08-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalevent',
            name='category',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='culturalevent',
            name='codename',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='culturalevent',
            name='date',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='culturalevent',
            name='guname',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='culturalevent',
            name='is_free',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='culturalevent',
            name='lat',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='culturalevent',
            name='lot',
            field=models.CharField(blank=True, max_length=30700),
        ),
        migrations.AlterField(
            model_name='culturalevent',
            name='org_name',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='culturalevent',
            name='place',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='culturalevent',
            name='themecode',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='culturalevent',
            name='ticket',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='culturalevent',
            name='title',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='culturalevent',
            name='use_fee',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='culturalevent',
            name='use_trgt',
            field=models.CharField(blank=True, max_length=700),
        ),
    ]
