# Generated by Django 5.2.4 on 2025-08-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_culturalevent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalevent',
            name='hmpg_addr',
            field=models.URLField(max_length=700),
        ),
        migrations.AlterField(
            model_name='culturalevent',
            name='lot',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='culturalevent',
            name='main_img',
            field=models.URLField(max_length=700),
        ),
        migrations.AlterField(
            model_name='culturalevent',
            name='org_link',
            field=models.URLField(max_length=700),
        ),
    ]
