"""
Django settings for Eiiii project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta
from celery.schedules import crontab
import dj_database_url

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Util
def _split_env_list(v: str | None, sep: str = ","):
    if not v:
        return []
    return [x.strip() for x in v.split(sep) if x.strip()]

def _env_bool(name: str, default: bool = False):
    return os.getenv(name, str(default)).lower() in ("1", "true", "yes", "y")

# Core
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY") or os.getenv("SECRET_KEY") or "CHANGE_ME_FOR_LOCAL_ONLY"
DEBUG = _env_bool("DJANGO_DEBUG", False)

ALLOWED_HOSTS = _split_env_list(os.getenv("ALLOWED_HOSTS")) or [
    "localhost", "127.0.0.1", "web", "nginx"
]
CSRF_TRUSTED_ORIGINS = _split_env_list(os.getenv("CSRF_TRUSTED_ORIGINS"))

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", False if DEBUG else True)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',

    'corsheaders',

    'home',
    'search',
    'details',

    'core',#연동 테스트용
    'accounts',#회원가입/로그인
    'category',#카테고리 클릭시 관련 행사 리스트 조회
    'profiles',#관심사 입력
    'surveys',#설문폼
    'point',#포인트
    'recommend',#추천로직
    'top3',#top3 조회
    'chatbot', #챗봇
    'pbrecommend' #비로그인 챗봇 추천
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "10/min",     # 비로그인 기준 분당 10회
    },
}
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),       # Access 토큰: 60분
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),          # Refresh 토큰: 7일
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'Eiiii.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Eiiii.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# 예: postgres://USER:PASS@HOST:PORT/DB
DATABASES = {
    "default": dj_database_url.parse(
        os.getenv("DATABASE_URL", ""), conn_max_age=600, ssl_require=False
    ) if os.getenv("DATABASE_URL")
    else {
        # 일단 지금 DATABASE_URL 없으니까 로컬 개발 편의용 SQLite
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# api key
SEOUL_OPENAPI_KEY = os.getenv("SEOUL_OPENAPI_KEY")
OPENAPI_BASE_URL = os.getenv("SEOUL_OPENAPI_BASE_URL")
KAKAO_API_KEY = os.getenv("KAKAO_REST_API_KEY")

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# === Static/Media via CloudFront (G1) ===
# 로컬 개발일 때는 기존처럼 /static/, /media/ 경로를 그대로 사용합니다.
# (즉, .env에 CF_STATIC_DOMAIN, CF_MEDIA_DOMAIN이 비어있으면 로컬 동작)
# 배포 환경에서는 CloudFront 도메인을 환경변수로 주입해서 CDN 경유로 전환합니다.

# CloudFront 도메인 (예: dxxxxx.cloudfront.net)
CF_STATIC_DOMAIN = os.getenv("CF_STATIC_DOMAIN")  # 정적(static/) 파일용
CF_MEDIA_DOMAIN  = os.getenv("CF_MEDIA_DOMAIN")   # 미디어(media/) 파일용 (없으면 STATIC 도메인과 동일하게 써도 됨)

# 정적/미디어 URL → CDN 도메인 기반으로 생성
STATIC_URL = f"https://{CF_STATIC_DOMAIN}/" if CF_STATIC_DOMAIN else "/static/"
STATIC_ROOT = "/app/staticfiles"  # collectstatic 실행 시 파일이 모이는 로컬 경로

MEDIA_URL  = f"https://{CF_MEDIA_DOMAIN}/" if CF_MEDIA_DOMAIN else "/media/"
MEDIA_ROOT = BASE_DIR / 'media'   # 업로드 파일이 저장되는 기본 경로 (S3에 업로드됨)

# === django-storages (S3 연동) ===
# django-storages + boto3를 통해 정적/미디어 파일을 자동으로 S3 버킷에 업로드하고,
# CloudFront가 그 파일을 캐싱/서빙할 수 있게 만듭니다.

AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")  # 예: myproj-app-assets
AWS_S3_REGION_NAME = os.getenv("AWS_REGION", "ap-northeast-2")  # 서울 리전 기본값
AWS_S3_SIGNATURE_VERSION = "s3v4"  # 권장 서명 방식
AWS_DEFAULT_ACL = None              # ACL은 비활성화 (OAC를 통해 접근 제어)
AWS_S3_ADDRESSING_STYLE = "virtual" # 가상 호스팅 스타일 권장

# === Django 앱 설정에 storages 추가 ===
INSTALLED_APPS += ["storages"]

# === Django STORAGES 백엔드 지정 ===
# staticfiles → StaticStorage (무조건 덮어쓰기, immutable 캐시)
# default → MediaStorage (파일명 유지, 캐시 없음)
STORAGES = {
    "staticfiles": {"BACKEND": "config.storages.StaticStorage"},
    "default":     {"BACKEND": "config.storages.MediaStorage"},
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'accounts.CustomUser'



# Cache / Celery

USE_REDIS = os.getenv("USE_REDIS", "1").lower() in ("1","true","yes","y")

if USE_REDIS:
    REDIS_URL = os.getenv("REDIS_URL") or os.getenv("REDIS_PUBLIC_URL") or "redis://localhost:6379/0"
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
        }
    }
    CELERY_BROKER_URL = REDIS_URL
    CELERY_RESULT_BACKEND = REDIS_URL
else:
    CACHES = {"default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache", "LOCATION": "local"}}
    CELERY_BROKER_URL = "memory://"
    CELERY_RESULT_BACKEND = "cache+memory://"


# Structured Logging (JSON) — G0에서 로그 모양 통일
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {"()": "pythonjsonlogger.jsonlogger.JsonFormatter"}
    },
    "handlers": {
        "stdout": {"class": "logging.StreamHandler", "formatter": "json"}
    },
    "root": {"handlers": ["stdout"], "level": "INFO" if not DEBUG else "DEBUG"},
}