"""
Django settings for Eiiii project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta
from celery.schedules import crontab
import dj_database_url

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Util
def _split_env_list(v: str | None, sep: str = ","):
    if not v:
        return []
    return [x.strip() for x in v.split(sep) if x.strip()]

def _env_bool(name: str, default: bool = False):
    return os.getenv(name, str(default)).lower() in ("1", "true", "yes", "y")

# Core
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY") or os.getenv("SECRET_KEY") or "CHANGE_ME_FOR_LOCAL_ONLY"
DEBUG = _env_bool("DJANGO_DEBUG", False)

ALLOWED_HOSTS = _split_env_list(os.getenv("ALLOWED_HOSTS")) or [
    "localhost", "127.0.0.1", "web", "nginx"
]
CSRF_TRUSTED_ORIGINS = _split_env_list(os.getenv("CSRF_TRUSTED_ORIGINS"))

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", False if DEBUG else True)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',

    'corsheaders',

    'home',
    'search',
    'details',

    'core',#연동 테스트용
    'accounts',#회원가입/로그인
    'category',#카테고리 클릭시 관련 행사 리스트 조회
    'profiles',#관심사 입력
    'surveys',#설문폼
    'point',#포인트
    'recommend',#추천로직
    'top3',#top3 조회
    'chatbot', #챗봇
    'pbrecommend' #비로그인 챗봇 추천
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "10/min",     # 비로그인 기준 분당 10회
    },
}
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),       # Access 토큰: 60분
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),          # Refresh 토큰: 7일
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'Eiiii.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Eiiii.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# 예: postgres://USER:PASS@HOST:PORT/DB
DATABASES = {
    "default": dj_database_url.parse(
        os.getenv("DATABASE_URL", ""), conn_max_age=600, ssl_require=False
    ) if os.getenv("DATABASE_URL")
    else {
        # 일단 지금 DATABASE_URL 없으니까 로컬 개발 편의용 SQLite
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# api key
SEOUL_OPENAPI_KEY = os.getenv("SEOUL_OPENAPI_KEY")
OPENAPI_BASE_URL = os.getenv("SEOUL_OPENAPI_BASE_URL")
KAKAO_API_KEY = os.getenv("KAKAO_REST_API_KEY")

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = "/app/staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'accounts.CustomUser'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cache / Celery

USE_REDIS = os.getenv("USE_REDIS", "1").lower() in ("1","true","yes","y")

if USE_REDIS:
    REDIS_URL = os.getenv("REDIS_URL") or os.getenv("REDIS_PUBLIC_URL") or "redis://localhost:6379/0"
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
        }
    }
    CELERY_BROKER_URL = REDIS_URL
    CELERY_RESULT_BACKEND = REDIS_URL
else:
    CACHES = {"default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache", "LOCATION": "local"}}
    CELERY_BROKER_URL = "memory://"
    CELERY_RESULT_BACKEND = "cache+memory://"


# Structured Logging (JSON) — G0에서 로그 모양 통일
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {"()": "pythonjsonlogger.jsonlogger.JsonFormatter"}
    },
    "handlers": {
        "stdout": {"class": "logging.StreamHandler", "formatter": "json"}
    },
    "root": {"handlers": ["stdout"], "level": "INFO" if not DEBUG else "DEBUG"},
}